# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - retris

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v2-beta
      with:
        node-version: '10.14'

    - run: npm install -g yarn
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn run build
        yarn test

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'retris'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_647a50ca5f0349c28afec4d919b7316d }}
        package: .